name: Test SQLite
on: [push, pull_request]

jobs:
  test-latest:
    name: "Active Record 8.0 + Ruby 3.4"
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/Gemfile.activerecord-8.0.x
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4"
          bundler-cache: true
      - name: Run the test suite against SQLite
        run: bundle exec rake test:sqlite3

  test-supported:
    name: "Active Record ${{ matrix.active_record }} + Ruby ${{ matrix.ruby }}"
    needs: [test-latest]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ["3.1", "3.2", "3.3", "3.4"]
        active_record: ["7.0", "7.1", "7.2"]
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/Gemfile.activerecord-${{ matrix.active_record }}.x
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          rubygems: ${{ matrix.rubygems }}
          bundler-cache: true
      - name: Run the test suite against SQLite
        run: bundle exec rake test:sqlite3
